users/urls.py
from django.contrib.auth import logout
from django.urls import path
from . import views #linking views.py's functions to our views.url links

urlpatterns  = [
    path('', views.allprofiles, name = 'profiles_link'),
    path('profile/<str:pk>/', views.userprofile,  name = 'user_profile_link'),

    path('login/', views.loginfxn, name = 'loginlink'),
    path('logout/',  views.logoutfxn , name = 'logoutlink'),
    path('register/', views.registerfxn, name = 'registerlink'),

    path('useraccount/', views.userAccountfxn, name = 'useraccount'),
    path('edit_account/', views.editAccountfxn, name = 'edit_acct'),
    path('create_skill/', views.createSkill, name = 'create-skill'),
    path('update_skill/<str:pk>/', views.updateSkill, name = 'update-skill'),
    path('delete_skill/<str:pk>/', views.deleteSkill, name = 'delete-skill'),

    path('inbox/', views.inbox, name = 'inbox'), 
    path('message/<str:pk>/', views.viewMessage, name = 'read_message'),
    path('create-message/<str:pk>/', views.createMessage, name = 'create_message'), 

]

users/models.py
from enum import auto
from django.db import models

from django.contrib.auth.models import User #we will be linking our profile to users table which is provided
#by django dada. we dont want to alter the users table generated by django, hence we creating the profile

import uuid

from django.db.models.deletion import SET_NULL
from django.db.models.fields import EmailField
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null = True)
    name = models.CharField(max_length=200, blank = True, null = True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null = True)
    location = models.CharField(max_length=200, blank=True, null = True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null = True)
    profile_image = models.ImageField(null = True, blank = True, upload_to = 'profiles/', default = 'profiles/user-default.png')
    social_github =models.CharField(max_length=200, blank = True, null = True)
    social_twitter =models.CharField(max_length=200, blank = True, null = True)
    social_linkedin =models.CharField(max_length=200, blank = True, null = True)
    social_youtube =models.CharField(max_length=200, blank = True, null = True)
    social_website =models.CharField(max_length=200, blank = True, null = True)

    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default = uuid.uuid4, unique = True, primary_key=True, editable = False)

    def __str__(self):      #this renders our objects readable
        return str(self.user.username)
 

class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null = True, blank = True)
    name = models.CharField(max_length=200,null = True, blank = True)
    description = models.TextField(null = True, blank = True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique = True, editable = False, primary_key=True)

    def __str__(self):
        return str(self.name) #someway somehow, dennis decided to add location to the Profile model/table

class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null = True , blank= True)   #on delete is set to null so dt upon deletion of sender's account, the msg remains in database. null is set to true so users sans account can send messages. blank is set to true cos a form can be submitted sans a sender.
    recepient = models.ForeignKey(Profile, on_delete=models.SET_NULL, null = True , blank= True, related_name='messages')   #on delete is set to null so dt upon deletion of sender's account, the msg remains in database. null is set to true so users sans account can send messages. blank is set to true cos a form can be submitted sans a sender.
    name = models.CharField(max_length=200, null =True, blank=True)
    email = models.EmailField(max_length=200, null =True, blank=True)
    subject = models.CharField(max_length=200, null =True, blank=True)
    body = models.TextField(max_length=200, null =True, blank=True)
    is_read = models.BooleanField(default=False, null = True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique = True, editable = False, primary_key=True)
    

    def __str__(self):
        return self.subject 
    
    class Meta:
        ordering = ['is_read', '-created'] 
        #unread messages will be at the top and if there is more than one it is arranged by date created in descending order

users/templates/users/account.html
{% extends 'main.html' %}

{% block content %}
  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit_acct' %}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="tempvar_profile.profile_image.url" />
              <h2 class="dev__name">{{tempvar_profile.name}}</h2>
              <p class="dev__title">{{tempvar_profile.short_intro}}</p>
              <p class="dev__location">Based in {{tempvar_profile.location}}, USA</p>
              
              
              <ul class="dev__social"> <!--22/12/21 we are going to delete the social tags adn copy and paste a smilar one from the user-profile template-->
                  <!-- from user-profile.html ==> ensure that percent sticks to curly brace and your code is centered, 2 prevent template error-->
                  {% if tempvar.social_github %} <!--- if there is input in social_github field, then render...-->
                  <li>
                    <a title="Github" href="#" target="_blank"><i class="im im-github"></i></a>
                  </li>
                  {% endif %}
                  
                  {% if tempvar.social_twitter %} <!--- if there is input in social_github field, then render...-->
                  <li>
                    <a title="Twitter" href="#" target="_blank"><i class="im im-twitter"></i></a>
                  </li>
                  {% endif %}
                  
                  {% if tempvar.social_linkedin %} <!--- if there is input in social_github field, then render...-->              
                  <li>
                    <a title="LinkedIn" href="#" target="_blank"><i class="im im-linkedin"></i></a>
                  </li>
                  {% endif %}
  
                  {% if tempvar.social_website %} <!--- if there is input in social_github field, then render...-->                
                  <li>
                    <a title="Personal Website" href="#" target="_blank"><i class="im im-globe"></i></a>
                  </li>
                  {% endif %} <!-- ensure that percent sticks to curly brace and endif is centered, 2 prevent template error-->
  
              </ul>


              <!--<a href="#" class="btn btn--sub btn--lg">Send Message </a> no need for a profilee to send itself  a message-->
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about"> {{tempvar_profile.bio}}</p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-skill' %}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
            {% for each in tempvar_skill %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{each.name}}</h4>
                <p>
                  {{each.description}}
                </p> 
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' each.id%}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' each.id%}"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}

          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'createproject' %}"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">
            {% for each in tempvar_project %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'fprojren' each.id %}"><img src="{{tempvar_project.featured_img.url}} " alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'fprojren' each.id %}">{{each.title}}</a>
                <p>
                  {{each.description|slice:'150'}} <!--slicing long description to not more than 150 chars-->
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'updateproject' each.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'deleteproject' each.id %}"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
           {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </main>

{% endblock %}

users/templates/users/edit_profile_form.html
{% extends 'main.html' %}

{% block content %}
 <!--step 5 == comment out the original-->
<!-- <h1> Edit Account </h1>
<form action="{% url 'edit_acct' %}" method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
    <!- rest to be handled by model forms->
    {{tempvar_form.as_p}}
    <input type="submit" value="Submit">
</form> -->

 <!-- Main Section -->
 <main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <!--step 4--> <a class="backButton" href="{% url 'useraccount' %}"> <i class="im im-angle-left"></i></a>
            <br>
          
            <!--step 1--><form class="form" action="{% url 'edit_acct' %}" method = "POST" enctype="multipart/form-data">
            <!--step 2-->    {% csrf_token %}

            <!--step 3a--> {% for field in tempvar_form %}
                             <!-- Input:Text -->
                            <div class="form__field">
                                <!--step 3a(i)-->   <label for="formInput#text">{{field.label}} </label>
                                <!--step 3a(ii)-><input class="input input--text" id="formInput#text" type="text" name="text" placeholder="Enter text" />-->
                                 <!--step 3a(iii)--> {{field}}
                            </div>
            <!--step 3b--> {% endfor %}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock %}

users/templates/users/inbox.html
{% extends 'main.html' %}

{% block content %}
  <!-- Main Section -->
  <main class="inbox my-xl">
    <div class="content-box">
      
      <!-- <h3 class="inbox__title">New Messages(<span>2</span>)</h3> -->
      <h3 class="inbox__title">New Messages(<span>{{temp_unreadCount}}</span>)</h3>

      <ul class="messages"> 
        {% for each_msg in temp_messageRequests %}

        {% if each_msg.is_read == False %}
        <li class="message message--unread">
          {% else %}
          <li class="message">    <!-- we deliberately commented out this closing tag</li> -->
          {% endif %}
          <a href="{% url 'read_message' each_msg.id %}">
            <!-- <span class="message__author">Dennis Ivanov</span> -->
            <span class="message__author">{{each_msg.name}}</span>

            <!-- <span class="message__subject">Working Opportunity for Web Design Company</span> -->
            <span class="message__subject">{{each_msg.subject}}</span>

            <!-- <span class="message__date">May 31, 2021, 04:37 PM</span> -->
            <span class="message__date">{{each_msg.created}}</span>

          </a>
        </li>
       {% endfor %}
      </ul>
    </div>
  </main>
  {% endblock content %}

users/templates/users/login_register.html
<!--This particular template will serve both as our register and login, but first we'll illustrate the login
Step 1: extend main and insert block tags   -->
{% extends 'main.html' %}
{% load static %}
{% block content %}


{% if tempvar_pagetype == 'register' %}
<!--
    <h1>Registration Page</h1>

    <form action="{% url 'registerlink' %}" method  = "POST">
        {% csrf_token %} <!- for security->
        {{tempvar_form.as_p}}
        <input type = "Submit" value = "Register User">
    </form>

    <p>Already have an account? <a href="{% url 'loginlink' %}" > Login</a></p>
-->
    <!-- 22.12.21 14:31 -->
    <div class="auth">
        <div class="card">
          <div class="auth__header text-center">
            <a href="/">
              <img src="{% static 'images/icon.svg' %}" alt="icon" />
            </a>
            <h3>Account SignUp</h3>
            <p>Create a new developer account</p>
          </div>
  
          <form action="{% url 'registerlink' %}" method  = "POST" class="form auth__form">
            {% csrf_token %}

                    {% for field in tempvar_form %}
                     <!-- Input:Text -->
                        <div class="form__field">
                        <label for="formInput#text">{{field.label}}</label>
                        {{field}}
                        
                        {% if field.help_text %}
                        <small>{{field.help_text}}</small> <!--small tags display text in small sizes-->
                        {% endif %}

                        {% for error in field.error %}
                        <p style = color:red> {{error}} </p> 
                        {% endfor %}
                    
                        </div>

                    {% endfor %}

           
            <div class="auth__actions"> 
              <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
            </div>
          </form>
          <div class="auth__alternative">
            <p>Already have an Account?</p>
            <a href="{%url 'loginlink'%}">Log In</a>
          </div>
        </div>
      </div>
{% else %}
    <!--
    <!- Step 2: build some form of a form, remember we're sending data with Post method so we'll need a csrf token--
    <form action="{% url 'loginlink' %}" method="POST"> <!- for now we leave the action field blank till we configure the urls ->
        {% csrf_token %}
        <input type = 'text' name = 'username' placeholder="Enter Username" \>
        <input type = 'password' name = 'password' placeholder="Enter Password" >
        <input type = 'submit' value="Login">
    
    <p> Don't have an account? <a href= "{% url 'registerlink' %}"> Sign Up</a>></p>
    </form>
-->
    <!-- 22/12/21 13:37 -->
   <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/icon.svg' %}" alt="icon" />
          </a> 
          <h3>Account Login</h3>
          <p>Hello Developer, Welcome Back!</p>
        </div>

        <!-- <form action="{% url 'loginlink' %}" method="POST" class="form auth__form"> -->
          <form action="" method="POST" class="form auth__form">
            {% csrf_token %}
 
            <!-- Input:Email  this will be our username -->
          <div class="form__field">
            <label for="formInput#text">Username: </label>
            <input
              class="input input--text"
              id="formInput#text"
              type="text"
              name="username"
              placeholder="Enter your username..."
            />
          </div>

          <!-- Input:Password -->
          <div class="form__field">
            <label for="formInput#password">Password: </label>
            <input
              class="input input--password"
              id="formInput#passowrd"
              type="password"
              name="password"
              placeholder="••••••••"
            />
          </div>
          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
            <a href="{% url 'reset_password' %}">Forget Password?</a>
          </div>
        </form>
        <div class="auth__alternative">
          <p>Don’t have an Account?</p>
          <a href="{% url 'registerlink' %}">Sign Up</a>
        </div>
      </div>
    </div>
{% endif %}


{% endblock content %}

<!--Step 3 move into our views.py and set a function to render this html, plus a link which will be slotted 
    into our form action attribute-->

users/templates/users/message.html
{% extends 'main.html' %}

{% block content %}
  <!-- Main Section -->
  <main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <!-- <a class="backButton" href="inbox.html"><i class="im im-angle-left"></i></a> -->
        <a class="backButton" href="{% url 'inbox' %}"><i class="im im-angle-left"></i></a>

        <!-- <h2 class="message__subject">Working Opportunity for Web Design Company</h4> -->
          <h2 class="message__subject">{{tempvar_msg.subject}}</h4>

          <a href="" class="message__author">{{tempvar_msg.name}}</a>
          <p class="message__date">{{tempvar_msg.created}}</p>
          <div class="message__body">   {{tempvar_msg.body|linebreaksbr}}          </div>
      </div>
    </div>
  </main>

  {% endblock content %}

users/templates/users/message_form.html
{% extends 'main.html'  %}

{% block content %}
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <!-- <a class="backButton" href="#"><i class="im im-angle-left"></i></a> -->
            <a class="backButton" href="{% url 'user_profile_link' tempvar_recepient.id %}"><i class="im im-angle-left"></i></a>

            <br>

            <form class="form" method="POST">
                {% csrf_token %}

                {% if request.user.is_authenticated == False %}   <!--in case user is an unauthenticated , we want them to add their name & email-->
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{tempvar_form.name.label}}</label>
                    <!-- <input class="input input--text" id="formInput#text" type="text" name="text" placeholder="Enter text" /> -->
                    {{tempvar_form.name}}
                </div>

                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{tempvar_form.email.label}}</label>
                    <!-- <input class="input input--text" id="formInput#text" type="text" name="text" placeholder="Enter text" /> -->
                    {{tempvar_form.email}}
                </div>
                {% endif %}

                <!-- these fields below are rendered irrespective if user is authenticated or not...    -->
                
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{tempvar_form.subject.label}}</label>
                    <!-- <input class="input input--text" id="formInput#text" type="text" name="text" placeholder="Enter text" /> -->
                    {{tempvar_form.subject}}
                </div>
                
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{tempvar_form.body.label}}</label>
                    <!-- <input class="input input--text" id="formInput#text" type="text" name="text" placeholder="Enter text" /> -->
                    {{tempvar_form.body}}
                </div>
                
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}
<h1> {{tempvar}}</h1>

<!--users app rendering profiles 17/11/21 10:23-->
  <!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form id = 'searchForm' class="form" action="{% url 'profiles_link' %}" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text"  name="search_query"
                placeholder="Search by developer name" value = {{tempvar_search_query}} >
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form> 
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
          
            <!-- deleted all but one column card -->
            {% for each in tempvar %}
          <div class="column card">
            <div class="dev">
 <!--HERE --> <a href="{% url 'user_profile_link' each.id %}" class="card__body">   <!--WHERE WE LINK IT-->
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{each.profile_image.url}}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{each.name}}</h3>
                    <h5>{{each.short_intro | slice:'60'}}</h5> 
                    <!--applied a pipe and added the slice method to show only 60chars -->
                  </div>
                </div>
                
                <p class="dev__info">   {{each.bio | slice:'150'}}  </p> <!--slices to 150 chars-->
                <div class="dev__skills">
                    {% for i in each.skill_set.all|slice:'5' %} <!--notice that this is an inner loop with the outer loop variable each -->
                  <span class="tag tag--pill tag--main">
                    <small>{{i}}</small>
                  </span>
                    {% endfor %}
                  
                </div>
              </a>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
    </section>

    {% include 'pagination.html' with queryset=tempvar custom_range=tempvar_custom_range%}
  <!--custom_range on the left is from the loop in pagination template and is assigned a value of the template variable from the views-->
  </main>

{% endblock %}

users/templates/users/skill_form.html
{% extends 'main.html' %}
{% block content %} 

<!-- <h1> Skill form</h1>
<form action="" method = 'POST'>
    {% csrf_token %}
    {{tempvar_form.as_p}}

    <input type="submit" value = "Submit">
</form>
 -->
 <!-- Main Section -->
 <main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'useraccount' %}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST" action="">
                {% csrf_token %}

                {%for field in tempvar_form %}
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{field.label}} </label>
                    <!--input class="input input--text" id="formInput#text" type="text" name="text" placeholder="Enter text" /-->
                    {{field}}
                </div>
                {% endfor %}

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}
{{tempvar}}

<!-- Main Section -->
<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{tempvar.profile_image.url}}" />
              <h2 class="dev__name">{{tempvar.name}}</h2>
              <p class="dev__title">{{tempvar.short_intro}}</p>
              <p class="dev__location">{{tempvar.location}}, USA</p>
              
              <ul class="dev__social">
                  <!-- ensure that percent sticks to curly brace and your code is centered, 2 prevent template error-->
                {% if tempvar.social_github %} <!--- if there is input in social_github field, then render...-->
                <li>
                  <a title="Github" href="#" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}
                
                {% if tempvar.social_twitter %} <!--- if there is input in social_github field, then render...-->
                <li>
                  <a title="Twitter" href="#" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}
                
                {% if tempvar.social_linkedin %} <!--- if there is input in social_github field, then render...-->              
                <li>
                  <a title="LinkedIn" href="#" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}

                {% if tempvar.social_website %} <!--- if there is input in social_github field, then render...-->                
                <li>
                  <a title="Personal Website" href="#" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %} <!-- ensure that percent sticks to curly brace and endif is centered, 2 prevent template error-->

              </ul>
              {% if request.user.profile.id != tempvar.id  %}
              <a href="{% url 'create_message' tempvar.id %}" class="btn btn--sub btn--lg">Send Message </a>
              {% endif %}
            </div>
          </div>
        </div>
        
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">     {{tempvar.bio}}     </p>
          </div>
          <div class="devInfo">
              <!--The Skills is gonna be tough but here we go...-->
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
              
                {% for each in temp_defskill %}
                <div class="devSkill">
                <h4 class="devSkill__title">{{each}}</h4>
                <p class="devSkill__info">          {{each.description}}             </p>
              </div>
                {% endfor %}
              

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                  {% for each in temp_otherskill %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{each}}</small>
                </span>
                    {% endfor %}
                
              </div>
            </div>
          </div>


          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">
            
                {% for proj in tempvar.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'fprojren' proj.id %}" class="project">
                    <img class="project__thumbnail" src="{{ proj.featured_img.url }}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{proj.title}}</h3>
                      <p><a class="project__author" href="">{{tempvar.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{proj.vote_ratio }}%</span> Postitive
                        Feedback ({{proj.vote_total}} Vote{{proj.vote_total|pluralize:'s'}})
                      </p>
                      
                      <div class="project__tags"> 
                        {% for tag in proj.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                       {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {% endfor %}

             

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock %}